export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_ESTATES = 'RECEIVE_ESTATES';
export const ADD_TO_SELECTED = 'ADD_TO_SELECTED';
